version: '3.8'
services: 
  vuetify-dashboard:
    container_name: 'frontend'
    build: .
    ports: ["8080:8080"]
    working_dir: /usr/app/src
    volumes: [./:/usr/app/src]
    command: yarn serve